services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=event-manager
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  # NestJS service
  nestjs:
    build:
      context: ./backend
    container_name: event-manager-backend
    environment:
      - DATABASE_URL=mongodb://root:password@mongodb:27017/event-manager
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - backend

  # React service
  react:
    build:
      context: ./frontend
    container_name: event-manager-frontend
    ports:
      - "5000:5000"
    depends_on:
      - nestjs
    networks:
      - backend

volumes:
  mongodb_data:
    driver: local

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
